name: Say Hello, World!

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print a message
        run: |
          echo "My secret value is: $SUPER_SECRET"
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
